### PR TITLE
handle fs errors

### LINKED ISSUE #144: fs: handle and return errors appropriately
`hearth-fs` performs file operations, most of which can fail. `hearth-types` defines the `fs` protocol, which includes a `Response` type that may contain errors. Right now, `hearth-fs` simply panics when any errors occur. We need to catch those errors and safely map them to `Response`s, adding more if necessary.

### PR DESCRIPTION
**Pull request by airidaceae**
closes #144

### CODE REVIEW

File: crates/hearth-fs/src/lib.rs [hunk 1]
```diff
@@ -16,16 +16,29 @@
...
     async_trait, cargo_process_metadata, hearth_types::fs::*, process::ProcessMetadata, utils::*,
 };
+use std::fs::{read, read_dir};
+use std::path::{Component, PathBuf};
 
 pub struct FsPlugin {
     root: PathBuf,
 }
 
+trait ToFsError<T, E> {
```
Comment (marceline-cramer) [inline crates/hearth-fs/src/lib.rs:29]: I really appreciate the sentiment behind this trait, but is there a reason to use this instead of [Result::map_err](https://doc.rust-lang.org/std/result/enum.Result.html#method.map_err)?

File: crates/hearth-fs/src/lib.rs [hunk 2]
```diff
@@ -35,35 +48,58 @@ impl RequestResponseProcess for FsPlugin {
         &'a mut self,
         request: &mut RequestInfo<'a, Request>,
     ) -> ResponseInfo<'a, Response> {
-        let target = match PathBuf::try_from(&request.data.target) {
-            Ok(target) => target,
-            Err(_) => return Error::InvalidTarget.into(),
-        };
+        match self.handle_request(request).await {
```
Comment (marceline-cramer) [inline crates/hearth-fs/src/lib.rs:51]: The match and `into()` here is redundant because `Result<Success, Error>`, which is what `handle_request` returns, is what `Response` is typedef'd to.

File: crates/hearth-fs/src/lib.rs [hunk 3]
```diff
@@ -35,35 +48,58 @@ impl RequestResponseProcess for FsPlugin {
...
+impl FsPlugin {
+    pub fn new(root: PathBuf) -> Self {
+        Self { root }
+    }
+
+    async fn handle_request<'a>(
+        &'a mut self,
+        request: &mut RequestInfo<'a, Request>,
+    ) -> Result<Success, Error> {
+        let target = PathBuf::try_from(&request.data.target).to_fs_error(Error::InvalidTarget)?;
```
Comment (marceline-cramer) [inline crates/hearth-fs/src/lib.rs:81]: This is fantastic and unwrap-free! Great job.

File: crates/hearth-fs/src/lib.rs [hunk 4]
```diff
@@ -35,35 +48,58 @@ impl RequestResponseProcess for FsPlugin {
...
         }
 
-        let success = match request.data.kind {
+        match request.data.kind {
             RequestKind::Get => {
-                let contents = match std::fs::read(path) {
-                    Ok(contents) => contents,
-                    Err(_) => todo!(),
-                };
+                let contents = read(path).to_fs_error(Error::NotFound)?;
```
Comment (marceline-cramer) [inline crates/hearth-fs/src/lib.rs:93]: Are there any IO errors that can be thrown by `read` other than `NotFound`?

File: crates/hearth-fs/src/lib.rs [hunk 5]
```diff
@@ -35,35 +48,58 @@ impl RequestResponseProcess for FsPlugin {
...
-                Success::Get(lump)
+                Ok(Success::Get(lump))
             }
             RequestKind::List => {
-                let dirs = match std::fs::read_dir(path) {
-                    Ok(dirs) => dirs,
-                    Err(_) => todo!(),
-                };
+                // read_dir can have multiple error differnt types of errors and
+                // im not sure of a good way to handle individual each one.
```
Comment (marceline-cramer) [inline crates/hearth-fs/src/lib.rs:101]: Perhaps something like:
```rs
use std::io::ErrorKind;
let dirs = match read_dir(path) {
    Ok(dirs) => dirs,
    Err(err) => {
        let err = match err.kind() {
            ErrorKind::Something => Error::SomethingError,
            _ => and_so_on!(),
        };

        return Err(err);
    }
};
```

**Review by marceline-cramer — CHANGES_REQUESTED** [review]
This is looking really, really good. I have a few questions about why you did some things and some ideas for other ways to do this but this is looking great and you should be proud.

File: crates/hearth-fs/src/lib.rs (hunk 1 above)
Comment (airidaceae) [reply crates/hearth-fs/src/lib.rs:29]: I think I just forgot that existed. Ill give it a try in the code and see how it works

File: crates/hearth-fs/src/lib.rs (hunk 4 above)
Comment (airidaceae) [reply crates/hearth-fs/src/lib.rs:93]: The kinds are as follows:
`Os(code: i32)`
`Custom(c)`
`Simple(kind: ErrorKind)` (which expands to so many things)
`SimpleMessage(SimpleMessage)` Which contains an ErrorKind and a message

I can handle these but it will likely be messy. ill see what it looks like.

Comment (airidaceae) [reply crates/hearth-fs/src/lib.rs:93]: wait no im silly. it should just give us ErrorKind

Comment (airidaceae) [reply crates/hearth-fs/src/lib.rs:93]: what do you think about a miscellaneous error type? theres only 2 or 3 kinds that are worth catching, `NotFound` `PermissionDenied`. We could have it contain a string for better debugging?

Comment (marceline-cramer) [reply crates/hearth-fs/src/lib.rs:93]: Sounds good to me.

Comment (marceline-cramer) [reply crates/hearth-fs/src/lib.rs:93]: And yeah, a string makes sense too.

**Comment by airidaceae** [comment]
The only thing left to do on this is to break some duplicate code out into its own function. From there its ready to merge.

**Review by marceline-cramer — APPROVED** [review]
Fantastic work, great job!
